### PR TITLE
Fix find_feasible_data timer

### PR DESCRIPTION
**Pull request by julie-vienne**
Issue #42

### CODE REVIEW

**Review by floracharbo — APPROVED** [review]

**Comment by floracharbo** [comment]
that looks good to me, you checked the `self.timer_optimisation[-1]` indeed made sense?

**Comment by julie-vienne** [comment]
I'll run some more tests with Euler to make sure it all makes sense. Currently, Euler is down.

**Comment by floracharbo** [comment]
> I'll run some more tests with Euler to make sure it all makes sense. Currently, Euler is down.

I meant more just putting a breakpoint at the line and inspecting the variables and operation. No need to run big experiments to validate this I don't think.

**Comment by julie-vienne** [comment]
@floracharbo I've run some checks and can confirm that this PR works and makes sense. Ready to merge :)

**Pull request merged**
