### PR TITLE
Fix optimisation errors with reactive power

### PR DESCRIPTION
**Pull request by floracharbo**

### CODE REVIEW

**Comment by floracharbo** [comment]
hi @julie-vienne. So this is now all fixed! Phew. That was tricky. I am wondering whether I have messed up with the iterations though, it takes up to 7 iterations to converge? Could you please have a look? The main change I've done here is the `check_and_correct_constraints` function.

**Comment by floracharbo** [comment]
with 

```
settings = {
    'RL': {
       'state_space': 'grdC',
       'n_epochs': 4,
       'n_repeats': 2,
       'type_learning': 'facmac'
    },
    'syst': {
        'n_homes': 40,
        'force_optimisation': True
    },
    'grd': {
        'pf_flexible_homes': 1,
        'manage_voltage': True,
        'line_losses_method': 'iteration',
        'compare_pandapower_optimisation': True,
        'manage_agg_power': True,
        'max_grid_import': 13,
        'max_grid_export': 13,
        'penalty_import': 0.01,
        'penalty_export': 0.01,
        'penalty_overvoltage': 0.1,
        'penalty_undervoltage': 0.1,
        'max_voltage': 1.001,
        'min_voltage': 0.999,
        'weight_network_costs': 1,
        'subset_line_losses_modelled': [20, 1],
        'reactive_power_for_voltage_control': False,
        'pf_passive_homes': 1.0,
    }
}
```

**Comment by floracharbo** [comment]
with `pf=0.95` only one iteration works. Maybe it is just move iterations for this extreme case. Do confirm I have not messed up with your method before I merge, but I hope this is all ok.

**Comment by julie-vienne** [comment]
@floracharbo here's a quick summary of the experiments I ran

- I was not able to test `pf_flexible_homes` before your fixes so I cannot say if they've worsened or improved the iteration.
- I think that a convergence under 7 steps with `pf_flexible_homes` is totally fine. I can't explain why the absence of reactive power makes it harder to converge though. Maybe we can discuss this with Eleni next week but as long it converges under 7 iterations, I'm not too worried.
-  I also checked some random optimization results and pandapower results and all seem to make sense, i.e. no obvious mistake would explain why it struggles to converge.
- I'm a little bit more worried about some assertion errors and non-convergence I got when running more experiments.
- For example with `pf_flexible_homes = 1.0`, 40 agents and q_learning on Euler:
  -  For one time step, it did not converge after 10 iterations:
max hourly delta voltages iteration 10: 0.0056009106586354385
max hourly delta losses iteration 10: 0.13040907897860876
  - For another time step, the following error, before it optimized for new values:
data_manager.py", line 549, in update_flexibility_opt
assert np.all(np.greater(flex_cons_opt, - self.tol_constraints * 2)), \
AssertionError: flex_cons_opt [-1.26325198e-04 -2.03692591e-05 -1.19275447e-04  9.13138834e-05
-1.25720092e-04 -1.45678141e-05 -6.36713116e-05 -7.15246613e-05
-1.17979591e-04  9.51960533e-05 -9.34225057e-06 -9.99077209e-05
-8.92317935e-05 -7.26554419e-05  2.20061559e-05 -7.12210652e-05
-9.48694878e-05 -1.36191658e-04 -7.69899057e-05  4.05372713e-05
4.03611478e-05  5.73256238e-05 -4.10729049e-05  4.69745642e-05
-1.32389750e-04 -8.21654937e-05  7.56821803e-05 -2.35097990e-02
-9.57818108e-05 -5.94578766e-05 -5.39882224e-05 -1.21906261e-04
-1.92529076e-05 -1.36715618e-04 -7.33963623e-05 -1.70325185e-05
-1.07804311e-04 -1.18418779e-04  2.41262931e-05 -1.02073812e-04]
- You're right, with `pf_flexible_homes = 0.95`, the convergence is reached very quickly. But again, I have some harmless (?) assertion errors before new values are optimized:
  - max hourly delta voltages initialization: 0.00422350369629898
max hourly delta losses initialization: 27.290375610077742
optimisation_post_processing.py", line 588, in _update_res_variables
assert np.all(abs(res[f'consa(0)'] + res[f'consa(1)'] + res['E_heat'] - res['totcons']) < 1e-3)
  - max hourly delta voltages initialization: 0.005507632294546538
max hourly delta losses initialization: 35.2987705677020
optimisation_post_processing.py", line 758, in res_post_processing
assert np.all(abs(res['hourly_line_losses'])  \
AssertionError: Hourly line losses are larger than 15% of the total import.
ex.args ('Hourly line losses are larger than 15% of the total import.',)
- I tried some tests on Euler with `pf_flexible_homes = 1.0`, q_learning and only 5 agents but it stopped running because of this:
optimisation_post_processing.py", line 588, in _update_res_variables
    assert np.all(abs(res[f'consa(0)'] + res[f'consa(1)'] + res['E_heat'] - res['totcons']) < 1e-3)

**Comment by julie-vienne** [comment]
@floracharbo except for the one time where it took 10 iterations and did not converge, I don't see any issues with this PR. Thank you again for solving this and cleaning everything up. It looks very good :)

**Review by floracharbo — COMMENTED** [review]
lint & merge

**Pull request merged**
