### PR TITLE
fix names recorded from network when manage_voltage

### PR DESCRIPTION
**Pull request by floracharbo**

### CODE REVIEW

**Comment by floracharbo** [comment]
These bugs for when `manage_voltage = True` could not be solved in PR #13 as there were optimisation errors that prevented me from running this setting at all.

**Comment by julie-vienne** [comment]
@floracharbo thanks for correcting this.

**Comment by julie-vienne** [comment]
Right now, we're replacing the voltage values if abs_voltage_diff > 1e-4 or rel_voltage_diff > 0.1). I think this might be a mistake. We should be making sure that the relative voltage difference is smaller than 1% (0.01) and not 10%, correct?
Also, I would like to correct the count of voltage errors like this to count of absolute and relative differences:

```
        if replace_with_pp_simulation:
            self.n_voltage_error += 1
```

We use `n_voltage_error` to print a warning message but it should actually be the same as `count_correction_opti_with_pp` that we print in record.

**Comment by julie-vienne** [comment]
Also, I would like to correct the count of voltage errors like this to count of absolute and relative differences:
> 
> ```
>         if replace_with_pp_simulation:
>             self.n_voltage_error += 1
> ```
> 
> We use `n_voltage_error` to print a warning message but it should actually be the same as `count_correction_opti_with_pp` that we print in record.

Nevermind this part, we're counting two different things with two different variables: the number of time we're replacing the values and the number of time the impact on the total costs in non-negligible. All good like this :) 
Except for the part where we're comparing the 10%

**Review by floracharbo — COMMENTED** [review]
ready to merge

**Comment by floracharbo** [comment]
> Right now, we're replacing the voltage values if abs_voltage_diff > 1e-4 or rel_voltage_diff > 0.1). I think this might be a mistake. We should be making sure that the relative voltage difference is smaller than 1% (0.01) and not 10%, correct? 

these should be set as input parameters in `grd` what tolerance you want to set.

**Review by floracharbo — COMMENTED** [review]
ready to merge

**Pull request merged**
