### PR TITLE
Not considering 'opt' in `type_actions`

### LINKED ISSUE #18: Optimization not running ?
See PR #17 
The optimization does not seem to be solved even though we would like our agents to learn from optimization results.

### LINKED ISSUE #21: print message to let user know when inputted evaluation_type is not valid
e.g. when doing opt_d_d with facmac, let user know that this is removed

### PR DESCRIPTION
**Pull request by julie-vienne**
image

### CODE REVIEW

**Comment by julie-vienne** [comment]
I might be wrong but as you can seen in `main.py`, we should be optimizing as we're trying to solve for `opt_d_d`. However, for me, `p.solve` is never called in the optimizer and `opt_needed` is set to False in `data_manager.py`

**Comment by julie-vienne** [comment]
I've also made sure that my folder opt_res and seed are empty.

**Comment by floracharbo** [comment]
This is because you should write the `evalution_methods` settings as:
`        'evaluation_methods': [['env_r_c', 'opt_d_d']] * 5,
`

Be careful that 
```
['env_r_c', 'opt_d_d'] * 5 = ['env_r_c',
  'opt_d_d',
  'env_r_c',
  'opt_d_d',
  'env_r_c',
  'opt_d_d',
  'env_r_c',
  'opt_d_d',
  'env_r_c',
  'opt_d_d']
```

so at the first iteration` prm['RL']['learning_methods'] = ['env_r_c']`

**Comment by julie-vienne** [comment]
@floracharbo ah yes, I see. Thanks. But then we should correct this in the `main.py` file that is currently in the repo as I believe this is how it's written in the settings there, right?

**Comment by floracharbo** [comment]
> @floracharbo ah yes, I see. Thanks. But then we should correct this in the `main.py` file that is currently in the repo as I believe this is how it's written in the settings there, right?

see https://github.com/floracharbo/MARL_local_electricity/pull/20#issuecomment-1407708321

I have committed one example for documentation purposes (so users can see how to input settings), and we should now stop committing local settings to the repo.

**Comment by julie-vienne** [comment]
This specific issue has been solved with commit e9adf9850b956bc1baaa7b07f09051733011a6e8 and PR #20

**Review by floracharbo — APPROVED** [review]
ready to merge.

**Pull request merged**
